services:
  people-api:
    build:
      context: . # Build context is the current directory (solution root)
      dockerfile: Dockerfile
    container_name: people-api
    ports:
      - "8080:8080" # Maps host port 8080 to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080